version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.31
    restart: always
    ports:
      - '3000:3000'
    environment:
      PRISMA_CONFIG: |
        port: 3000
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-225-113-7.compute-1.amazonaws.com
            database: d46jaum0f5dklu
            schema: public
            user: pbuxiyqvzrdkmp
            password: 5c795c2bd69231ce1766b533f7c06b62d3bbf6da818c6b80da4dffc2a451c771
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
